### ISSUE TITLE
Source of inspiration?

### ISSUE THREAD

**Issue by developit** [aweary/enzyme-adapter-preact#4]
I'm wondering if some of the internals here could be implemented based on [mzgoddard/preact-render-spy](https://github.com/mzgoddard/preact-render-spy)?

**Comment by aweary** [comment]
Hey @developit! I've been using `preact-render-spy` when I'm able to work on this, it's been helpful with understanding how to implement the adapter 👍  Since the APIs are defined by Enzyme, there's not too much crossover between this adapter and `preact-render-spy`, so using it as a starting point for implementation will have limited success. 

I've implemented the most important, which is converting the Preact tree to the React Standard Tree (RST) format, so APIs like `find` are already functional. The major pending tasks are:

* Shallow rendering
* State and prop updates
* Simulating events

**Comment by apunov** [comment]
@aweary also really looking forward to preact switch, so really hope to keep all of our tests alive!
You're totally right, 99% of jsx tests are: shallow / find (dive/get/at) / setState / simulate('click')
Could you please let us know if there's any ETA on that one?

**Comment by awinogradov** [comment]
Solved by https://github.com/aweary/enzyme-adapter-preact/pull/6
